language: generic

sudo: required

env:
    global:
        - IMAGE=menski/test-travis-docker

services:
    - docker

script:
    - docker build -t $IMAGE:SNAPSHOT .

after_success:
    - docker tag $IMAGE:SNAPSHOT $IMAGE:7.4.0-SNAPSHOT
    - docker tag $IMAGE:SNAPSHOT $IMAGE:tomcat-SNAPSHOT
    - docker tag $IMAGE:SNAPSHOT $IMAGE:tomcat-7.4.0-SNAPSHOT
    - docker images
