language: generic

sudo: required

services:
  - docker

script:
    - docker build -t camunda/camunda-bpm-platform:SNAPSHOT .

after_success:
    - docker tag camunda/camunda-bpm-platform:SNAPSHOT camunda/camunda-bpm-platform:7.4.0-SNAPSHOT
    - docker tag camunda/camunda-bpm-platform:SNAPSHOT camunda/camunda-bpm-platform:tomcat-SNAPSHOT
    - docker tag camunda/camunda-bpm-platform:SNAPSHOT camunda/camunda-bpm-platform:tomcat-7.4.0-SNAPSHOT
